# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Clojure in Belgium
email: hello@beclojure.org
description: > # this means to ignore newlines until "baseurl:"
  A group of enthusiasts that have at least one thing in common - we
  are all passionate about the Clojure philosophy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://beclojure.org" # the base hostname & protocol for your site
twitter_username: beclojure
github_username:  beclojure

# Build settings
markdown: kramdown
